### PR TITLE
Handsome refactoring and upgrades (I am going to kill god)

### PR DESCRIPTION
**Pull request by luciusmagn**
Gentlemen, there is a couple of TODOs, but I still want to show you this cock.

This essentially rewrites testauskameli in such away, that you can reasonably easily add backends (shit like language playgrounds, latex, no meme?) and such that you can also somewhat easily add frontends (Discord, cli, http, whatever)

To create a backend:
- Create a structure
- Implement `MrSnippet` on it (named so in honor of Luukasa)

To create a frontend:
- Do whatever you need to make a bot or sumshit
- Create a structure, which has some way to hold `MrSnippet` trait objects, such that it is valid in an async, Send + Sync, interior mutability context
- Implement `Executor` on said structure

To run the executor then, you just need to spawn a tokio::task that awaits the future from `Executor::run`.

You then send it inputs via a `flume` channel (in async mode, or youre mom gay), and with the `Context` type that you need to set for the executor trait, the executor will send the response messages automatically.

This is a WIP, here is a couple outstanding issues that I know of:
- I want to implement the cli frontend, so that it is easier to test testauskameli locally
- It needs testing
- Haskell schizma:
    - The async Command provides both methods for unlimited and constrained execution
    - I think it is better to call shell scripts which do appropriate amount of limitation for languages like Haskell which need to be compiled, and thus these should be passed in there as env variables and the final call of the shell script shall be the sudo with s6 limits
    - Things that can be run directly better use the Command with limitations, ie. shell scripts
    - I don't have the haskell script yet lmao
 
The async command can also automatically create temporary directories and files to run the code in. The run methods which use any of the temporary IO return a FIles object along with a future in a tuple.

The Future is the actual command, awaiting it will run it.

The Files is a guard for the temporary files, once it's dropped, da files are gone

### CODE REVIEW

**Comment by luciusmagn** [comment]
Another TODO is that no meme? is not concurrency safe, one call can preempt another and the wrong or worse, a corrupted image may be sent. Which would be incredibly funny, though

**Comment by lajp** [comment]
> Another TODO is that no meme? is not concurrency safe, one call can preempt another and the wrong or worse, a corrupted image may be sent. Which would be incredibly funny, though

Yes, so far the development of this project has been focusing on functionality over correctness, but tissues like this are to be considered in the future.

**Comment by luciusmagn** [comment]
It is an easy fix

**Comment by luciusmagn** [comment]
> > Another TODO is that no meme? is not concurrency safe, one call can preempt another and the wrong or worse, a corrupted image may be sent. Which would be incredibly funny, though
> 
> Yes, so far the development of this project has been focusing on functionality over correctness, but tissues like this are to be considered in the future.

fixed in [dc49297](https://github.com/Testausserveri/testauskameli/pull/3/commits/dc4929763198f58d1c32f1da38d93bb57e3cc806) and [fa78d83](https://github.com/Testausserveri/testauskameli/pull/3/commits/fa78d839498b05ce7e9ea74704ee06551dbebc66)

**Comment by lajp** [comment]
LGTM! Let's kill god!

**Pull request merged**
